myproject/myproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("order/", include("order.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/order/urls.py
from django.urls import path
from . import views

app_name = "order"

urlpatterns = [
    path("", views.LandingView, name="landing"),
    path("aboutus/", views.AboutUsView, name="aboutus"),
    path("address/", views.AddressView, name="address"),
    path("category/", views.CategoryView, name="category"),
    path("customer/", views.CustomerView, name="customer"),
    path("discount/", views.DiscountView, name="discount"),
    path("driver/", views.DriverView, name="driver"),
    path("food/", views.FoodView, name="food"),
    path("restaurant/", views.RestaurantView, name="restaurant"),
    path("user/", views.UserView, name="user"),
]

myproject/order/models.py
from django.db import models

# Create your models here.

myproject/order/views.py
import json

from datetime import datetime
from django.http import JsonResponse
from django.shortcuts import render

from .services import run_query, sha256


def LandingView(request):
    return render(request, "landing.html")

def AboutUsView(request):
    return render(request, "aboutus.html")

def AddressView(request):
    if request.method == "POST":
        data = request.POST

        postal_code = data.get("postal_code")
        title = data.get("title")
        city = data.get("city")
        street = data.get("street")
        phone_number = data.get("phone_number")
        latitude = data.get("latitude")
        longitude = data.get("longitude")

        # Validate the input data
        if not postal_code or not city or not street:
            return JsonResponse({"error": "Required fields are missing"}, status=400)

        try:
            run_query(
                """
                INSERT INTO address (postal_code, title, city, street, phone_number, latitude, longitude) 
                VALUES (%s, %s, %s, %s, %s, %s, %s)
            """,
                [postal_code, title, city, street, phone_number, latitude, longitude],
            )
        except Exception as e:
            return JsonResponse({"error": str(e)}, status=500)

    query = "SELECT postal_code, title, city, street, phone_number, latitude, longitude FROM address"
    data = run_query(query)
    context = {"data": data}
    return render(request, "address.html", context)


def CategoryView(request):
    if request.method == "POST":
        data = request.POST

        name = data.get("name")

        try:
            run_query(
                """
                INSERT INTO category (name) 
                VALUES (%s)
            """,
                [name],
            )
        except Exception as e:
            return JsonResponse({"error": str(e)}, status=500)

    query = "SELECT id, name FROM category"
    data = run_query(query)
    context = {"data": data}
    return render(request, "category.html", context)


def CustomerView(request):
    if request.method == "POST":
        data = request.POST

        user_id = data.get("id")
        nat_code = data.get("nat_code")
        adr = data.get("adr")

        try:
            run_query(
                """
                INSERT INTO customer (user_id, nat_code, default_address)
                VALUES (%s, %s, %s)
            """,
                [user_id, nat_code, adr],
            )
        except Exception as e:
            return JsonResponse({"error": str(e)}, status=500)

    query = "SELECT user_id, name, nat_code, phone_num, default_address FROM view_customer_info;"
    data = run_query(query)
    context = {"data": data}
    return render(request, "customer.html", context)


def DiscountView(request):
    if request.method == "POST":
        data = request.POST

        amount = data.get("amount")
        type = data.get("type")
        expire_time = data.get("expire_time")

        try:
            # Convert expire_time to the correct format
            expire_time = datetime.strptime(expire_time, "%Y-%m-%dT%H:%M")
            expire_time = expire_time.strftime("%Y-%m-%d %H:%M:%S")

            run_query(
                """
                INSERT INTO discount (amount, type, expire_time) 
                VALUES (%s, %s, %s)
            """,
                [amount, type, expire_time],
            )
        except Exception as e:
            return JsonResponse({"error": str(e)}, status=500)

    query = "SELECT discount_code, amount, type, expire_time FROM discount"
    data = run_query(query)
    formatted_data = [
        (item[0], item[1], item[2], item[3].strftime("%Y-%m-%dT%H:%M:%S"))
        for item in data
    ]

    query = "SELECT discount_code, amount, type, expire_time FROM available_discounts"
    available_data = run_query(query)
    formatted_available_data = [
        (item[0], item[1], item[2], item[3].strftime("%Y-%m-%dT%H:%M:%S"))
        for item in available_data
    ]

    context = {
        "data": json.dumps(formatted_data),
        "available_data": json.dumps(formatted_available_data),
    }
    return render(request, "discount.html", context)

def DriverView(request):
    if request.method == "POST":
        data = request.POST

        user_id = data.get("id")
        car_tag = data.get("car_tag")

        try:
            run_query(
                """
                INSERT INTO driver (user_id, car_tag)
                VALUES (%s, %s)
            """,
                [user_id, car_tag],
            )
        except Exception as e:
            return JsonResponse({"error": str(e)}, status=500)

    query = "SELECT user_id, name, car_tag, phone_num FROM view_driver_info;"
    data = run_query(query)
    context = {"data": data}
    return render(request, "driver.html", context)


def FoodView(request):
    if request.method == "POST":
        data = request.POST

        name = data.get("name")
        price = data.get("price")
        category = data.get("category")
        description = data.get("description")
        image = data.get("image")

        print(category)
        try:
            run_query(
                """
                INSERT INTO food (name, price, description, image, category_id)
                VALUES (%s, %s, %s, %s, %s)
            """,
                [name, price, description, image, category],
            )
        except Exception as e:
            return JsonResponse({"error": str(e)}, status=500)

    query = "SELECT f.id, f.name, price, c.name, description, image FROM food f JOIN category c ON (f.category_id=c.id)"
    data = run_query(query)

    query = "SELECT id,name FROM category"
    categories = run_query(query)

    context = {"data": data, "categories": categories}
    return render(request, "food.html", context)

def RestaurantView(request):
    if request.method == "POST":
        data = request.POST

        name = data.get("name")
        create_time = data.get("create_time")
        adr = data.get("adr")

        try:
            run_query(
                """
                INSERT INTO restaurant ( name, create_time, address)
                VALUES (%s, %s, %s)
            """,
                [name, create_time, adr],
            )
        except Exception as e:
            return JsonResponse({"error": str(e)}, status=500)

    query = "SELECT id, name, create_time, address FROM restaurant;"
    data = run_query(query)
    context = {"data": data}
    return render(request, "restaurant.html", context)


def UserView(request):
    if request.method == "POST":
        data = request.POST

        name = data.get("name")
        password = data.get("password")
        phone_num = data.get("phone_num")
        email = data.get("email")
        identify_code = data.get("identify_code")

        password_hash = sha256(password)

        try:
            run_query(
                """
                INSERT INTO users (name, password, phone_num, email, identify_code)
                VALUES (%s, %s, %s, %s, %s)
            """,
                [name, password_hash, phone_num, email, identify_code],
            )
        except Exception as e:
            return JsonResponse({"error": str(e)}, status=500)

    query = "SELECT id, name, password, phone_num, email, identify_code FROM users"
    data = run_query(query)
    context = {"data": data}
    return render(request, "user.html", context)

myproject/order/templates/aboutus.html
{% extends "base.html" %}

{% block title %}About Us{% endblock %}

{% block bodyHeader %}
    <header class="bg-gray-800 text-white p-4">
        <div class="container mx-auto">
            <h1 class="text-2xl font-semibold">About Us</h1>
            <a href="{% url 'order:landing' %}" class="block text-l font-semibold text-white"> 
                Back
            </a>
        </div>
    </header>
{% endblock %}

{% block content %}
    <div class="container mt-10">
        <h4>Welcome to our Online Food Ordering System! This platform is the result of a collaborative project undertaken in the Database Laboratory at Isfahan University of Technology.</h4>
        <br />

        <h4>Our team, consisting of <a href="https://github.com/shirinbehnami">Shirin Behnaminia</a>, <a href="https://github.com/sabzparto">Parto Sabzevari</a>, and <a href="https://github.com/Narges-Mntzr">Narges Montazeri</a>, has developed this system to streamline and enhance the food ordering process. The primary goal of this project is to apply our theoretical knowledge of database management in a practical setting, creating a functional and user-friendly application that meets modern requirements.</h4>
        <br />

        <h4>Through this project, we aimed to integrate various database techniques, ensuring efficient data handling and seamless user experiences. We hope our system demonstrates the potential of database applications in real-world scenarios, particularly in the food and beverage industry.</h4>
        <br />

        <h4>Thank you for visiting, and we hope you enjoy exploring our project!</h4>
    </div>
{% endblock %}

{% block bodyFooter %}
{% endblock %}

myproject/order/templates/address.html
{% extends "base.html" %}

{% block title %}Addresses{% endblock %}

{% block bodyHeader %}
    <header class="bg-gray-800 text-white p-4">
        <div class="container mx-auto">
            <h1 class="text-2xl font-semibold">Addresses</h1>
            <a href="{% url 'order:landing' %}" class="block text-l font-semibold text-white"> 
                Back
            </a>
        </div>
    </header>
{% endblock %}

{% block content %}
    <div class="container">
        <table class="table table-bordered">
            <thead class="bg-gray-800 text-white p-4">
                <tr>
                    <th>Postal Code</th>
                    <th>Title</th>
                    <th>City</th>
                    <th>Street</th>
                    <th>Phone Number</th>
                    <th>Latitude</th>
                    <th>Longitude</th>
                </tr>
            </thead>
            <tbody>
                {% for adr in data %}
                    <tr>
                        <td>{{ adr.0 }}</td>
                        <td>{{ adr.1 }}</td>
                        <td>{{ adr.2 }}</td>
                        <td>{{ adr.3 }}</td>
                        <td>{{ adr.4 }}</td>
                        <td>{{ adr.5 }}</td>
                        <td>{{ adr.6 }}</td>
                    </tr>
                {% endfor %}
                <tr class="add-row">
                    <form method="post">{% csrf_token %}
                        <td><input type="number" name="postal_code" class="form-control" placeholder="Postal Code" required></td>
                        <td><input type="text" name="title" class="form-control" placeholder="Title"></td>
                        <td><input type="text" name="city" class="form-control" placeholder="City" required></td>
                        <td><input type="text" name="street" class="form-control" placeholder="Street" required></td>
                        <td><input type="tel" name="phone_number" class="form-control" placeholder="Phone Number"></td>
                        <td><input type="text" name="latitude" class="form-control" placeholder="Latitude"></td>
                        <td><input type="text" name="longitude" class="form-control" placeholder="Longitude"></td>
                        <td><button type="submit" class="btn btn-success">Add</button></td>
                    </form>
                </tr>
            </tbody>
        </table>
        <div id="map"></div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
    <script>
        var map = L.map('map').setView([51.505, -0.09], 2);  // Default view centered globally
        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            maxZoom: 18,
        }).addTo(map);

        {% for adr in data %}
            L.marker([{{ adr.5 }}, {{ adr.6 }}]).addTo(map)
                .bindPopup('<b>{{ adr.1 }}</b><br>PostalCode: {{ adr.0 }}')
                .openPopup();
        {% endfor %}
    </script>
{% endblock %}

{% block bodyFooter %}
{% endblock %}

myproject/order/templates/category.html
{% extends "base.html" %}

{% block title %}Categories{% endblock %}

{% block bodyHeader %}
    <header class="bg-gray-800 text-white p-4">
        <div class="container mx-auto">
            <h1 class="text-2xl font-semibold">Categories</h1>
            <a href="{% url 'order:landing' %}" class="block text-l font-semibold text-white"> 
                Back
            </a>
        </div>
    </header>
{% endblock %}

{% block content %}
    <div class="container">
        <table class="table table-bordered">
            <thead class="bg-gray-800 text-white p-4">
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                </tr>
            </thead>
            <tbody>
                {% for category in data %}
                    <tr>
                        <td>{{ category.0 }}</td>
                        <td>{{ category.1 }}</td>
                    </tr>
                {% endfor %}
                <tr class="add-row">
                    <form method="post">{% csrf_token %}
                        <td><input type="number" name="id" class="form-control" placeholder="ID" disabled></td>
                        <td><input type="text" name="name" class="form-control" placeholder="Title" required></td>
                        <td><button type="submit" class="btn btn-success">Add</button></td>
                    </form>
                </tr>
            </tbody>
        </table>
    </div>
{% endblock %}

{% block bodyFooter %}
{% endblock %}

myproject/order/templates/customer.html
{% extends "base.html" %}

{% block title %}Customer{% endblock %}

{% block bodyHeader %}
    <header class="bg-gray-800 text-white p-4">
        <div class="container mx-auto">
            <h1 class="text-2xl font-semibold">Customer</h1>
            <a href="{% url 'order:user' %}" class="block text-l font-semibold text-white"> 
                Back
            </a>
        </div>
    </header>
{% endblock %}

{% block content %}
    <div class="container">
        <table class="table table-bordered">
            <thead class="bg-gray-800 text-white p-4">
                <tr>
                    <th>User Id</th>
                    <th>Name</th>
                    <th>National Code</th>
                    <th>Phone Number</th>
                    <th>Postal Code</th>
                </tr>
            </thead>
            <tbody>
                {% for customer in data %}
                    <tr>
                        <td>{{ customer.0 }}</td>
                        <td>{{ customer.1 }}</td>
                        <td>{{ customer.2 }}</td>
                        <td>{{ customer.3 }}</td>
                        <td>{{ customer.4 }}</td>
                    </tr>
                {% endfor %}
                <tr class="add-row">
                    <form method="post">{% csrf_token %}
                        <td><input type="number" name="id" class="form-control" placeholder="User Id" required></td>
                        <td><input type="text" name="name" class="form-control" placeholder="Name" disabled></td>
                        <td><input type="number" name="nat_code" class="form-control" placeholder="National Code"></td>
                        <td><input type="tel" name="phone_num" class="form-control" placeholder="Phone Number" disabled></td>
                        <td><input type="text" name="adr" class="form-control" placeholder="Postal Code"></td>
                        <td><button type="submit" class="btn btn-success">Add</button></td>
                    </form>
                </tr>
            </tbody>
        </table>
    </div>
{% endblock %}

{% block bodyFooter %}
{% endblock %}

myproject/order/templates/discount.html
{% extends "base.html" %}

{% block title %}Discounts{% endblock %}

{% block bodyHeader %}
<header class="bg-gray-800 text-white p-4">
    <div class="container mx-auto">
        <h1 class="text-2xl font-semibold">Discounts</h1>
        <a href="{% url 'order:landing' %}" class="block text-l font-semibold text-white">
            Back
        </a>
    </div>
</header>
{% endblock %}

{% block content %}
<div class="container">
    <div class="p-4 mb-4 rounded col-md-4">
        <div class="container mx-auto flex items-center">
            <input type="checkbox" id="dataSwitch" style="width: 20px;" class="form-control mr-2" onclick="switchData()">
            <label for="dataSwitch" class="form-check-label text-lg">Display Available Discounts</label>
        </div>
    </div>
    <table class="table table-bordered">
        <thead class="bg-gray-800 text-white p-4">
            <tr>
                <th>Discount Code</th>
                <th>Amount</th>
                <th>Percent</th>
                <th>Cash</th>
                <th>Expire Time</th>
            </tr>
        </thead>
        <tbody id="discountTable">
            <!-- Data will be dynamically rendered here -->
        </tbody>
        <tbody>
            <tr class="add-row">
                <form method="post">
                    {% csrf_token %}
                    <td><input type="number" name="discount_code" class="form-control" placeholder="Discount Code" disabled></td>
                    <td><input type="number" name="amount" class="form-control" placeholder="Amount"></td>
                    <td><input type="checkbox" name="type" class="form-control" value="percent" onclick="onlyOne(this)"></td>
                    <td><input type="checkbox" name="type" class="form-control" value="cash" onclick="onlyOne(this)"></td>
                    <td><input type="datetime-local" name="expire_time" class="form-control"></td>
                    <td><button type="submit" class="btn btn-success">Add</button></td>
                </form>
            </tr>
        </tbody>
    </table>
</div>
<script>
    var data = JSON.parse('{{ data|escapejs }}');
    var availableData = JSON.parse('{{ available_data|escapejs }}');

    function switchData() {
        var useAvailableData = document.getElementById('dataSwitch').checked;
        renderTable(useAvailableData);
    }

    function renderTable(useAvailableData) {
        var tableBody = document.getElementById('discountTable');
        tableBody.innerHTML = ''; // Clear previous content

        var dataSet = useAvailableData ? availableData : data;

        dataSet.forEach(function(discount) {
            var row = document.createElement('tr');
            row.innerHTML = `
                <td>${discount[0]}</td>
                <td>${discount[1]}</td>
                <td><input type="checkbox" class="form-control" ${discount[2] === 'percent' ? 'checked disabled' : 'disabled'}></td>
                <td><input type="checkbox" class="form-control" ${discount[2] === 'cash' ? 'checked disabled' : 'disabled'}></td>
                <td>${discount[3]}</td>
            `;
            tableBody.appendChild(row);
        });
    }

    function onlyOne(checkbox) {
        var checkboxes = document.getElementsByName('type');
        checkboxes.forEach((item) => {
            if (item !== checkbox) item.checked = false;
        });
    }

    // Initial rendering
    renderTable(false); // Render default data
</script>
{% endblock %}

{% block bodyFooter %}
{% endblock %}

myproject/order/templates/driver.html
{% extends "base.html" %}

{% block title %}Drivers{% endblock %}

{% block bodyHeader %}
    <header class="bg-gray-800 text-white p-4">
        <div class="container mx-auto">
            <h1 class="text-2xl font-semibold">Drivers</h1>
            <a href="{% url 'order:user' %}" class="block text-l font-semibold text-white"> 
                Back
            </a>
        </div>
    </header>
{% endblock %}

{% block content %}
    <div class="container">
        <table class="table table-bordered">
            <thead class="bg-gray-800 text-white p-4">
                <tr>
                    <th>User Id</th>
                    <th>Name</th>
                    <th>Car Tag</th>
                    <th>Phone Number</th>
                </tr>
            </thead>
            <tbody>
                {% for driver in data %}
                    <tr>
                        <td>{{ driver.0 }}</td>
                        <td>{{ driver.1 }}</td>
                        <td>{{ driver.2 }}</td>
                        <td>{{ driver.3 }}</td>
                    </tr>
                {% endfor %}
                <tr class="add-row">
                    <form method="post">{% csrf_token %}
                        <td><input type="number" name="id" class="form-control" placeholder="User Id" required></td>
                        <td><input type="text" name="name" class="form-control" placeholder="Name" disabled></td>
                        <td><input type="text" name="car_tag" class="form-control" placeholder="Car Tag"></td>
                        <td><input type="tel" name="phone_num" class="form-control" placeholder="Phone Number" disabled></td>
                        <td><button type="submit" class="btn btn-success">Add</button></td>
                    </form>
                </tr>
            </tbody>
        </table>
    </div>
{% endblock %}

{% block bodyFooter %}
{% endblock %}

myproject/order/templates/food.html
{% extends "base.html" %}
{% load static %}

{% block title %}Food{% endblock %}

{% block bodyHeader %}
    <header class="bg-gray-800 text-white p-4">
        <div class="container mx-auto">
            <h1 class="text-2xl font-semibold">Food</h1>
            <a href="{% url 'order:landing' %}" class="block text-l font-semibold text-white"> 
                Back
            </a>
        </div>
    </header>
{% endblock %}

{% block content %}
    <div class="container">
        <table class="table table-bordered">
            <thead class="bg-gray-800 text-white p-4">
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Category</th>
                    <th>Description</th>
                    <th>Image</th>
                </tr>
            </thead>
            <tbody>
                {% for food in data %}
                    <tr>
                        <td>{{ food.0 }}</td>
                        <td>{{ food.1 }}</td>
                        <td>{{ food.2 }}$</td>
                        <td>{{ food.3 }}</td>
                        <td>{{ food.4 }}</td>
                        <td><img src="{% static '' %}{{ food.5 }}" alt="{{ food.1 }}" width="100" height="100"></td>
                    </tr>
                {% endfor %}
                <tr class="add-row">
                    <form method="post">{% csrf_token %}
                        <td><input type="number" name="id" class="form-control" placeholder="ID" disabled></td>
                        <td><input type="text" name="name" class="form-control" placeholder="Title" required></td>
                        <td><input type="number" name="price" class="form-control" placeholder="Price" required></td>
                        <td>
                            <select name="category" class="form-control">
                                {% for choice in categories %}
                                    <option value="{{ choice.0 }}" class="form-control">{{ choice.1 }}</option>
                                {% endfor %}
                            </select>
                        </td>
                        <td><input type="text" name="description" class="form-control" placeholder="Description"></td>
                        <td><input type="file" name="image" accept="image/*"></td>
                        <td><button type="submit" class="btn btn-success">Add</button></td>
                    </form>
                </tr>
            </tbody>
        </table>
    </div>
{% endblock %}

{% block bodyFooter %}
{% endblock %}

myproject/order/templates/landing.html
{% extends "base.html" %}

{% block title %}Admin Panel{% endblock %}

{% block bodyHeader %}
    <header class="bg-gray-800 text-white p-4">
        <div class="container mx-auto">
            <h1 class="text-2xl font-semibold">Admin Panel</h1>
            <a href="{% url 'order:aboutus' %}" class="block text-l font-semibold text-white">
                ABOUT US
            </a>
        </div>
    </header>
{% endblock %}

{% block content %}
<div class="text-center">
    <h2 class="mb-5 mt-5 font-semibold">Welcome to Food Ordering App</h1>
    <div class="btn-container">
        <div class="btn-wrapper">
            <a href="{% url 'order:address' %}" class="btn btn-primary btn-custom ">Addresses</a>
        </div>
        <div class="btn-wrapper">
            <a href="{% url 'order:category' %}" class="btn btn-success btn-custom">Categories</a>
        </div>
        <div class="btn-wrapper">
            <a href="{% url 'order:discount' %}" class="btn btn-info btn-custom">Discounts</a>
        </div>
        <div class="btn-wrapper">
            <a href="{% url 'order:food' %}" class="btn btn-primary btn-custom">Food</a>
        </div>
        <div class="btn-wrapper">
            <a href="{% url 'order:user' %}" class="btn btn-success btn-custom">Users</a>
        </div>
    </div>
</div>
{% endblock %}

{% block bodyFooter %}
{% endblock %}

myproject/order/templates/restaurant.html
{% extends "base.html" %}

{% block title %}Restaurants{% endblock %}

{% block bodyHeader %}
    <header class="bg-gray-800 text-white p-4">
        <div class="container mx-auto">
            <h1 class="text-2xl font-semibold">Restaurants</h1>
            <a href="{% url 'order:user' %}" class="block text-l font-semibold text-white"> 
                Back
            </a>
        </div>
    </header>
{% endblock %}

{% block content %}
    <div class="container">
        <table class="table table-bordered">
            <thead class="bg-gray-800 text-white p-4">
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Create Time</th>
                    <th>Address</th>
                </tr>
            </thead>
            <tbody>
                {% for rest in data %}
                    <tr>
                        <td>{{ rest.0 }}</td>
                        <td>{{ rest.1 }}</td>
                        <td>{{ rest.2 }}</td>
                        <td>{{ rest.3 }}</td>
                    </tr>
                {% endfor %}
                <tr class="add-row">
                    <form method="post">{% csrf_token %}
                        <td><input type="number" name="id" class="form-control" placeholder="ID" disabled></td>
                        <td><input type="text" name="name" class="form-control" placeholder="Name"></td>
                        <td><input type="datetime-local" name="create_time" class="form-control"></td>
                        <td><input type="text" name="adr" class="form-control" placeholder="Address"></td>
                        <td><button type="submit" class="btn btn-success">Add</button></td>
                    </form>
                </tr>
            </tbody>
        </table>
    </div>
{% endblock %}

{% block bodyFooter %}
{% endblock %}

myproject/order/templates/user.html
{% extends "base.html" %}

{% block title %}Users{% endblock %}

{% block bodyHeader %}
    <header class="bg-gray-800 text-white p-4">
        <div class="container mx-auto">
            <h1 class="text-2xl font-semibold">Users</h1>
            <a href="{% url 'order:landing' %}" class="block text-l font-semibold text-white"> 
                Back
            </a>
        </div>
    </header>
{% endblock %}

{% block content %}
    <div class="container">
        <table class="table table-bordered">
            <thead class="bg-gray-800 text-white p-4">
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Password</th>
                    <th>Phone Number</th>
                    <th>Email</th>
                    <th>Identify Code</th>
                </tr>
            </thead>
            <tbody>
                {% for user in data %}
                    <tr>
                        <td>{{ user.0 }}</td>
                        <td>{{ user.1 }}</td>
                        <td>{{ user.2 }}</td>
                        <td>{{ user.3 }}</td>
                        <td>{{ user.4 }}</td>
                        <td>{{ user.5 }}</td>
                    </tr>
                {% endfor %}
                <tr class="add-row">
                    <form method="post">{% csrf_token %}
                        <td><input type="number" name="id" class="form-control" placeholder="ID" disabled></td>
                        <td><input type="text" name="name" class="form-control" placeholder="Title" required></td>
                        <td><input type="password" name="password" class="form-control" placeholder="Password" required></td>
                        <td><input type="tel" name="phone_num" class="form-control" placeholder="Phone Number"></td>
                        <td><input type="email" name="email" class="form-control" placeholder="Email" required></td>
                        <td><input type="number" name="identify_code" class="form-control" placeholder="Identify Code" required></td>
                        <td><button type="submit" class="btn btn-success">Add</button></td>
                    </form>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="btn-container">
        <div class="btn-wrapper">
            <a href="{% url 'order:customer' %}" class="btn btn-primary btn-custom-user ">Customer</a>
        </div>
        <div class="btn-wrapper">
            <a href="{% url 'order:restaurant' %}" class="btn btn-primary btn-custom-user">Restaurant</a>
        </div>
        <div class="btn-wrapper">
            <a href="{% url 'order:driver' %}" class="btn btn-primary btn-custom-user">Driver</a>
        </div>
    </div>
{% endblock %}

{% block bodyFooter %}
{% endblock %}